# Generated by Django 2.2 on 2020-02-11 17:22

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userprofile_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to=app.models.content_file_name),
        ),
    ]
